### ISSUE TITLE
Versioning & breaking API changes

### ISSUE THREAD

**Issue by Profpatsch** [spell-music/data-fix#10]
[`hnix` broke recently because of a version change](https://github.com/jwiegley/hnix/issues/63).
It’s impossible to add a version bound at the moment, because there is no distinction between API-breaking changes and additions.

Would you be okay with switching to the second digit and incrementing it when a breaking API-change happens? Then `hnix` could depend on e.g. `==0.2.*`.

cc @jwiegley

**Comment by anton-k** [comment]
So, do i need to just upgrade the version and keep the code the same?

**Comment by Profpatsch** [comment]
Yeah, that would be possible. Maybe switch to `0.0.7.0` directly and add it to the changelog as changing to a more semantic versioning scheme.

**Comment by anton-k** [comment]
Done
