### ISSUE TITLE
Not an issue - just a question about the haskell type system that came to my mind by looking at data-fix

### ISSUE THREAD

**Issue by alaendle** [spell-music/data-fix#24]
Please excuse if this is a dumb question 😃 

Maybe I just missing some special Haskell syntax - but I don't find a good explanation for:

```
type MyMaybe :: Type -> Type
type MyMaybe = Maybe

type MyMaybe' :: Type -> Type
type MyMaybe' a = Maybe a

type Works = Fix MyMaybe

-- • The type synonym ‘MyMaybe'’ should have 1 argument, but has been given none
-- • In the type synonym declaration for ‘DoesntWork’
type DoesntWork = Fix MyMaybe'
```

Here for sure the argument can be avoided - but what if the type is nested - e.g. something like `Either (Maybe a ) ()`? How to apply `Fix` in such a case?

**Comment by anton-k** [comment]
In Haskell we can not use type-synonyms as functions from type to type. Type synonyms should always be fully applied. 
You can solve it by declaring the type (using data or newtype).

**Comment by alaendle** [comment]
Thanks!
