### ISSUE TITLE
Add to Stackage

### ISSUE THREAD

**Issue by ndmitchell** [spell-music/data-fix#3]
Nice package - have you thought about adding it to Stackage? I'm using it and it would make my life easier. See https://github.com/fpco/stackage/blob/master/MAINTAINERS.md#adding-a-package for details.

**Comment by anton-k** [comment]
I'm glad that you find it useful. I'll think it over

**Comment by anton-k** [comment]
Ok, I've made a pull request on stackage to add data-fix.

**Comment by anton-k** [comment]
@ndmitchell  My pull request was merged. Can you try it out. If it's ok, I'll close the issue

**Comment by ndmitchell** [comment]
It's in Stackage, which is all I was after, and let's me remove it from my custom stack.yaml and get faster rebuilds. Many thanks!
