### ISSUE TITLE
Use Eq1, Show1, etc. for instances

### ISSUE THREAD

**Issue by andrewthad** [spell-music/data-fix#6]
Since `base-4.9`, the `Data.Functor.Classes` module has been available (previously, it was available through the `transformers` library). It would be nice if the instances for `Fix` relied on these instead of using `FlexibleContexts`. I am willing to PR this if you would accept it.

**Comment by anton-k** [comment]
PRs are welcome! 

But can you make it with conditionals on GHC version. So that it should work in previous versions of GHC

**Comment by andrewthad** [comment]
Absolutely.

**Comment by andrewthad** [comment]
PR is up
